server:
  port: 8080

logging:
  level:
    ROOT: INFO
    love.korni: DEBUG
    love.korni.shopexample: TRACE

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./uploads/shopexample
    username: user
    password: password
  liquibase:
    url: jdbc:h2:file:./uploads/shopexample
    user: user
    password: password
    change-log: db/changelog/database_coffee_shop_changelog.xml
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    show-sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tags-sorter: alpha
